configs:
  cm:
    admin.enabled: true
  secret:
    argocdServerAdminPassword: "$2y$12$WrFi3Wg3FxoV7tZ3AdC2LOkbZ2zHc2v67TJ99UEkB1ukI2skoCQSu"

global:
  domain: ${argo_host}

controller:
  serviceType: ClusterIP

crds:
  install: true
  keep: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/"
      cert-manager.io/cluster-issuer: "letsencrypt"
    hostname: ${argo_host}
    path: /
    pathType: Prefix
    tls: true
    tlsSecret: argocd-server-tls

