apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: git@github.com:Hendawyy/3-Tier-K8s-CD.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBBQxNbMKjRf5UrAos6rZoR95VH21PYPQMDBRIo4r9ZzAAAAKDBB0kNwQdJ
    DQAAAAtzc2gtZWQyNTUxOQAAACBBQxNbMKjRf5UrAos6rZoR95VH21PYPQMDBRIo4r9ZzA
    AAAEDhNRnYNA3qQy+aEoCzNFXgmcT/vRpj0kYGpzXo3HUAtkFDE1swqNF/lSsCizqtmhH3
    lUfbU9g9AwMFEijiv1nMAAAAFnNlaWZoZW5kYXd5MUBnbWFpbC5jb20BAgMEBQYH
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLFS: "false"
